sudo: required

dist: trusty

language: cpp

env:
  - export NODE_VERSION="6"

os:
  - linux
  - osx

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.yarn-cache

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
    packages:
      - xvfb

before_install:
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - git submodule update --init --recursive
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm config set python `which python`

install:
  - export CXX="g++-4.8"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update              ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install imagemagick ; fi
  - yarn
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16";
      export DISPLAY=':99.0';
      Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & echo "nothing";
      sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils xorriso imagemagick;
    fi

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - node --version
  - yarn --version
  - yarn run test
  - yarn run package
  - yarn run bench-api
  # - yarn run test-screenshot
