environment:
  matrix:
    - nodejs_version: 6

cache:
  - 'node_modules'

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

cache:
 - "%LOCALAPPDATA%/Yarn"

install:
  - choco install yarn
  - refreshenv
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - yarn
  

test_script:
  - node --version
  - yarn --version
  - yarn run test
  - yarn run package
  # - yarn run bench-api
  # - yarn run test-screenshot
